[tool.poetry]
name = "python-base-flake"
version = "0.1.0"
description = ""
authors = [ "Chaz Schlarp <schlarpc@gmail.com>" ]

[tool.poetry.dependencies]
# not automatically used by poetry2nix - https://github.com/nix-community/poetry2nix/issues/570
python = "^3.9"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
mypy = "^0.942"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"

[tool.poetry.scripts]
python-base-flake = "python_base_flake._cli:main"

[tool.black]
line-length = 99

[tool.coverage]
run.source_pkgs = [ "python_base_flake" ]
run.branch = true
report.show_missing = true

[tool.isort]
combine_as_imports = true
line_length = 99
profile = "black"
skip_gitignore = true
src_paths = [ "src", "tests" ]

[tool.mypy]
check_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
warn_return_any = true
warn_unused_ignores = true
files = [ "src", "tests" ]

[tool.pytest.ini_options]
addopts = "--cov"
testpaths = [ "tests" ]

[build-system]
requires = [ "poetry-core>=1.0.0" ]
build-backend = "poetry.core.masonry.api"
