name: Generate template

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: .github/scripts/generate-template.sh
      - uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: template
          FOLDER: .template
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
