name: Test

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: DeterminateSystems/nix-installer-action@v20
      - run: nix build
      - run: nix flake check
